# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night:
  font: native
  font_size: L

# SEO

marketing:
  seo:
    site_type: EducationalOrganization
    local_business_type: 'University'
    org_name: 'Northern Arizona University School of Earth and Sustainability'
    description: 'Leading research and education in earth sciences, environmental sustainability, geology, climate science, and conservation at Northern Arizona University. Graduate and undergraduate programs, faculty research, and student opportunities.'
    twitter: 'nau_ses'
  analytics:
    google_analytics: 'G-1J3WD3SGQN'
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false
  custom_head: true

# Social media links
social:
  twitter: 'https://twitter.com/nau_ses'
  facebook: 'https://www.facebook.com/NAUSESAZ/'
  instagram: 'https://www.instagram.com/nau_ses/'
  youtube: 'https://www.youtube.com/@nauschoolofearthsustainability'
  bluesky: 'https://nau-ses.bsky.social/'

# Site footer

footer:
  copyright:
    notice: '© {year} NAU School of Earth and Sustainability. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: ''
  time_format: ''
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  hide_dates: true
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Custom CSS
custom_css: ["css/custom.css"]

# Citation style

publications:
  date_format: January 2006
  citation_style: apa
